import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Sidebar from "@/ui/Sidebar";
import { Suspense } from "react";
import Loading from "./loading";
import {NextUIProvider} from "@nextui-org/react";
import NavbarComponent from "@/ui/NavbarComponent";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

      <html>
        <body>
        <NextUIProvider>
          <div className="dark">
            <NavbarComponent></NavbarComponent>
            <div className="flex h-screen flex-col md:flex-row md:overflow-hidden ">
              <div className="w-full flex-none md:w-64">
                <Sidebar></Sidebar>
              </div>
              <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
                <Suspense fallback={<Loading></Loading>}>
                  {children}
                </Suspense>
              </div>
            </div>
          </div>
          </NextUIProvider>
        </body>
      </html>

  );
}