version: '3.1'

services:

  db:
    container_name: feedlify
    image: postgres:13.9
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
    ports:
      - "5432:5432"
